export async function testt(page) {
//Buying Power
await page.getByRole('button', { name: 'Compliance' }).click();
await page.getByRole('link', { name: 'Buying Power' }).click();
await page.locator('input[name="fromDate"]').fill('2020-01-01');
await page.locator('input[name="toDate"]').fill('2025-02-13');
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Correspondent').click();
await page.getByRole('option', { name: 'SASS' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByRole('button', { name: 'Rerun Buying Power' }).click();
await page.getByLabel('Rerun', { exact: true }).check();
await page.getByRole('button', { name: 'Process' }).click();
await page.getByTestId('headcol-4').click();
await page.getByTestId('headcol-4').click();

//Call Logs
await page.getByRole('button', { name: 'Compliance' }).click();
await page.getByRole('link', { name: 'Call Logs' }).click();
await page.locator('input[name="fromDate"]').fill('2020-01-01');
await page.locator('input[name="toDate"]').fill('2025-02-13');
await page.getByLabel('Correspondent').click();
await page.getByRole('option', { name: 'SASS' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByRole('checkbox', { name: 'Open' }).check();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Pending').click();
await page.getByRole('option', { name: 'Overdue' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Overdue').click();
await page.getByRole('option', { name: 'Satisfied' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Satisfied').click();
await page.getByRole('emphasis').click();
await page.locator('#mui-component-select-callStatus').click();
await page.getByRole('option', { name: 'Blank' }).click();
await page.locator('#mui-component-select-callStatusReason').click();
await page.getByRole('option', { name: 'ACH/Wire Received' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('ACH/Wire Received').click();
await page.getByRole('option', { name: 'ACH/Wire Initiated' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('ACH/Wire Initiated').click();
await page.getByRole('option', { name: 'Auto Satisfy' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Auto Satisfy').click();
await page.getByRole('option', { name: 'Call Error' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Call Error').click();
await page.getByRole('option', { name: 'Liquidated' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Liquidated').click();
await page.getByRole('option', { name: 'PDT Attestation Received' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('PDT Attestation Received').click();
await page.getByRole('option', { name: 'Blank' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();

//Cash Call Log
await page.getByRole('button', { name: 'Compliance' }).click();
await page.getByRole('link', { name: 'Cash Call Log' }).click();
await page.locator('input[name="fromDate"]').fill('2020-01-01');
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Blank').click();
await page.getByRole('option', { name: 'Close' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Close').click();
await page.getByRole('option', { name: 'Extended' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Extended').click();
await page.getByRole('option', { name: 'Free Riding' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Free Riding').click();
await page.getByRole('option', { name: 'Outstanding' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
await page.getByLabel('Outstanding').click();
await page.getByRole('option', { name: 'Pending' }).click();
await page.locator('button').filter({ hasText: 'Search' }).click();
const page2Promise = page.waitForEvent('popup');
await page.getByTestId('MuiDataTableBodyCell-1-0').getByLabel('view').click();
const page2 = await page2Promise;
}